db_edit:
    resource: "@DbBundle/Resources/config/routing/overall.yml"
    prefix:   /edit

db_edit1:
    resource: "@DbBundle/Resources/config/routing/pstats.yml"
    prefix:   /edit1

db_edit2:
    resource: "@DbBundle/Resources/config/routing/tstats.yml"
    prefix:   /edit2

db_homepage:
    path:     /
    defaults: { _controller: DbBundle:Default:index }

db_graph:
    path:     /graph
    defaults: { _controller: DbBundle:Graph:index }

db_graphp:
    path:     /graphp
    defaults: { _controller: DbBundle:Graphp:index }

login:
  path: /login
  defaults: { _controller: DbBundle:Security:login }

login_check:
  path: /login_check

logout:
  pattern: /logout
