# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
      Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
      ROLE_ADMIN: [ROLE_USER]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:

        chain_provider:
          chain:
            providers: [in_memory]

        in_memory:
            memory:
              users:
                admin: {password: admin, roles: ROLE_ADMIN}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /.*
            form_login:
              login_path: /login
              check_path: /login_check
              default_target_path: /edit
            logout:
              path: /logout
              target: /
              invalidate_session: false
            security: true
            anonymous: true

    access_control:
          - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: /graph, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: /graphp, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: /.*, roles: ROLE_ADMIN }

