edit1_index:
    path:     /
    defaults: { _controller: "DbBundle:PStats:index" }
    methods:  GET

edit1_show:
    path:     /{id}/show
    defaults: { _controller: "DbBundle:PStats:show" }
    methods:  GET

edit1_new:
    path:     /new
    defaults: { _controller: "DbBundle:PStats:new" }
    methods:  [GET, POST]

edit1_edit:
    path:     /{id}/edit
    defaults: { _controller: "DbBundle:PStats:edit" }
    methods:  [GET, POST]

edit1_delete:
    path:     /{id}/delete
    defaults: { _controller: "DbBundle:PStats:delete" }
    methods:  DELETE
