edit2_index:
    path:     /
    defaults: { _controller: "DbBundle:TStats:index" }
    methods:  GET

edit2_show:
    path:     /{id}/show
    defaults: { _controller: "DbBundle:TStats:show" }
    methods:  GET

edit2_new:
    path:     /new
    defaults: { _controller: "DbBundle:TStats:new" }
    methods:  [GET, POST]

edit2_edit:
    path:     /{id}/edit
    defaults: { _controller: "DbBundle:TStats:edit" }
    methods:  [GET, POST]

edit2_delete:
    path:     /{id}/delete
    defaults: { _controller: "DbBundle:TStats:delete" }
    methods:  DELETE
